{
 "title": "JMX Dashboard(Basic)",
 "description": "jmx exporter monitor",
 "tags": [
  "jmx",
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job='jmx'}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JDK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"jmx\", instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jmx\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{job=\"jmx\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{job=\"jmx\", instance=\"$instance\"} / 1000"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=\"jmx\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{job=\"jmx\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{job=\"jmx\", instance=\"$instance\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Process Load(1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_ProcessCpuLoad{job=\"jmx\", instance=\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"jmx\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory util",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (100 * java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"jmx\", instance=\"$instance\"} / on(instance) java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"jmx\", instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalSwapSpaceSize{job=\"jmx\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SWAP util",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreeSwapSpaceSize{job=\"jmx\", instance=\"$instance\"} / on(instance) java_lang_OperatingSystem_TotalSwapSpaceSize{job=\"jmx\", instance=\"$instance\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"jmx\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=\"jmx\", instance=\"$instance\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"jmx\", instance=\"$instance\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"jmx\", instance=\"$instance\"} / on(instance) java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"jmx\", instance=\"$instance\"})  ",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "Memory JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Used (Heap/NonHeap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "NonHeap"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap/NonHeap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jmx\", instance=\"$instance\"} / ignoring(area) group_left java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"jmx\", instance=\"$instance\"} *100",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Memory Committed (Heap/NonHeap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_committed{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "NonHeap"
    }
   ]
  },
  { "title": "Memory JVM Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory Pool Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Pool Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"jmx\", instance=\"$instance\"}[1m])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"jmx\", instance=\"$instance\"}[1m])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "java_lang_Threading_DaemonThreadCount{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Class Loading count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "java_lang_ClassLoading_UnloadedClassCount{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "currently"
    },
    {
     "expr": "jvm_classes_loaded_total{job=\"jmx\", instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  }
 ]
}